# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

cache:
  - C:\RLibrary

environment:
  global:
    _R_CHECK_CRAN_INCOMING_: 0

  matrix:
  #- R_VERSION: release
  #  R_ARCH: i386
  #  R_BUILD_ARGS: --no-build-vignettes
  #  R_CHECK_ARGS: --ignore-vignettes --no-vignettes --no-manual
    
  - R_VERSION: release
    R_ARCH: x64


# Adapt as necessary starting from here

build_script:
  - travis-tool.sh install_deps
  - cmd: Rscript -e "is.null(install.packages(c('taxstats', 'taxstats1516'), repos = 'https://hughparsonage.github.io/tax-drat'))"

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
