---
title: "Performance of project"
author: "Hugh Parsonage"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Performance of project}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## How well does the project function work one year in advance?

```{r echo=FALSE}
knitr::opts_chunk$set(fig.width = 6)
```

```{r, echo=FALSE}

required_packages <-
  c("testthat", 
    "taxstats",
    "dplyr",
    "rmarkdown", 
    "dtplyr",
    "ggplot2",
    "scales", 
    "broom", 
    "knitr",
    "survey", 
    "viridis",
    "ggrepel")

required_packages_present <-
  all(vapply(required_packages, requireNamespace, quietly = TRUE, FALSE))

knitr::opts_chunk$set(message = FALSE, 
                      eval = required_packages_present)
```

```{r message=FALSE}
library(knitr)
library(data.table)
if (requireNamespace("taxstats", quietly = TRUE) &&
    packageVersion("taxstats") >= package_version("0.0.5") &&
    !identical(Sys.getenv("NOT_CRAN"), "true")) {
  library(taxstats)
} else {
  templib <- file.path(tempdir(), "perf")
  hutils::provide.dir(templib)
  install.packages("taxstats",
                   lib = templib,
                   repos = "https://hughparsonage.github.io/drat/",
                   type = "source")
  library("taxstats", lib.loc = templib)
}

sample_files_all <-
    rbindlist(lapply(list(`2003-04` = sample_file_0304, 
                          `2004-05` = sample_file_0405, `2005-06` = sample_file_0506, 
                          `2006-07` = sample_file_0607, `2007-08` = sample_file_0708, 
                          `2008-09` = sample_file_0809, `2009-10` = sample_file_0910, 
                          `2010-11` = sample_file_1011, `2011-12` = sample_file_1112, 
                          `2012-13` = sample_file_1213, `2013-14` = sample_file_1314), 
                     data.table::as.data.table),
              use.names = TRUE,
              fill = TRUE, 
              idcol = "fy.year")
sample_files_all[, WEIGHT := hutils::if_else(fy.year > '2010-11', 50L, 100L)]
library(grattan)
library(dtplyr)
library(dplyr)
library(magrittr)
library(ggplot2)
library(scales)
library(broom)
```

To test the performance of our projection, we consider the projection of the 2012-13 sample file by one year with the actual 2013-14 sample file.

```{r}
sample_file_1314_projected <- 
  sample_file_1213 %>%
  copy %>%
  mutate(WEIGHT = 50) %>%
  project(h = 1L,
          fy.year.of.sample.file = "2012-13",
          .recalculate.inflators = TRUE) %>%
  .[]
```


```{r}
data.table(the_source = c("Actual",
                          "Projected"),
           n_persons = c(nrow(sample_file_1314) * 50,
                         sum(sample_file_1314_projected$WEIGHT)), 
           avg_Taxable_Income = c(mean(sample_file_1314$Taxable_Income),
                                  mean(sample_file_1314_projected$Taxable_Income)),
           avg_Sw = c(mean(sample_file_1314$Sw_amt),
                      mean(sample_file_1314_projected$Sw_amt))
) %>% 
  melt.data.table(id.vars = "the_source") %>%
  group_by(variable) %>%
  mutate(value_rel = value / first(value)) %>%
  # dcast.data.table(variable ~ the_source) %>%
  ggplot(aes(x = variable, y = value_rel, fill = the_source)) + 
  geom_bar(stat = "identity", position = "dodge") + 
  geom_text(aes(label = comma(round(value))),
            position = position_dodge(width = 0.9),
            hjust = 1.02) + 
  coord_flip() + 
  theme(legend.position = "top")
```

```{r}
conf_int_of_t.test <- function(variable){
  t_test <- t.test(sample_file_1314[[variable]],
                   sample_file_1314_projected[[variable]])
  t_test %>%
    tidy(.) %>%
    mutate(var = variable) %>%
    as.data.table
}

c("Sw_amt",
  "Net_rent_amt",
  "Net_CG_amt",
  "Tot_inc_amt",
  "Tot_ded_amt",
  "Taxable_Income") %>%
  lapply(conf_int_of_t.test) %>%
  rbindlist %>%
  .[, list(var, conf.low, conf.high, p.value)] %>%
  ggplot(aes(x = var,
             ymin = conf.low,
             ymax = conf.high,
             color = p.value > 0.05)) + 
  geom_errorbar() + 
  geom_hline(yintercept = 0)
```

## Years not in sample files

Other tests can be found in the `tests/` folder to compare the tax collections in those years. 






