version: 2
jobs:
  build:
    working_directory: ~/main
    docker:
      - image: rocker/verse
        environment:
          NOT_CRAN: true
          TRAVIS: true
          
    parallelism: 2
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps1-{{ .Branch }}-{{ checksum "DESCRIPTION" }}-{{ checksum ".circleci/config.yml" }}
            - deps1-{{ .Branch }}
            - deps1-
      - run:
          command: |
            Rscript -e "devtools::install_deps(dependencies = TRUE)"
      - run:
          no_output_timeout: 20m
          command: |
            Rscript -e 'dir.create("~/.R");file.create(mv <- "~/.R/Makevars");writeLines("CXXFLAGS=-O3", mv)'
            if [[ $CIRCLE_NODE_INDEX == "0" ]]; then R CMD build --no-build-vignettes . ; fi
            if [[ $CIRCLE_NODE_INDEX == "0" ]]; then R CMD check *tar.gz ; fi
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "DESCRIPTION" }}-{{ checksum ".circleci/config.yml" }}
          paths:
            - "/usr/local/lib/R/site-library"
      - run:
          no_output_timeout: 20m
          command: |
            mkdir /root/main/artifacts
            if [[ $CIRCLE_NODE_INDEX == "1" ]]; then Rscript -e "devtools::install()" ; fi
            if [[ $CIRCLE_NODE_INDEX == "1" ]]; then Rscript -e "knitr::knit('vignettes/grattan.Rmd')" ; fi
      - store_artifacts:
          path: /root/main/artifacts/
          destination: artifacts
