# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pmax3 <- function(x, y, z) {
    .Call('grattan_pmax3', PACKAGE = 'grattan', x, y, z)
}

pmaxC <- function(x, a) {
    .Call('grattan_pmaxC', PACKAGE = 'grattan', x, a)
}

pmaxV <- function(x, y) {
    .Call('grattan_pmaxV', PACKAGE = 'grattan', x, y)
}

pminC <- function(x, a) {
    .Call('grattan_pminC', PACKAGE = 'grattan', x, a)
}

pminV <- function(x, y) {
    .Call('grattan_pminV', PACKAGE = 'grattan', x, y)
}

squish_cpp <- function(x, a, b) {
    .Call('grattan_squish_cpp', PACKAGE = 'grattan', x, a, b)
}

